// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0wdVRwE_19E4pnOE8hUKC7h903UOEm78',
    appId: '1:259364934462:web:c6ea794c16b8234e4d126f',
    messagingSenderId: '259364934462',
    projectId: 'ase-urhg',
    authDomain: 'ase-urhg.firebaseapp.com',
    storageBucket: 'ase-urhg.firebasestorage.app',
    measurementId: 'G-WBNYXJX4G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcVTmOV5HDSI7hhhUJ0vzGQuo9CRdgIWE',
    appId: '1:259364934462:android:a746e95c8bd959d34d126f',
    messagingSenderId: '259364934462',
    projectId: 'ase-urhg',
    storageBucket: 'ase-urhg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8MB4e2P8OG_ydu5-lPQxqXQJUMqG3Ro',
    appId: '1:259364934462:ios:01ea01cdaefc24184d126f',
    messagingSenderId: '259364934462',
    projectId: 'ase-urhg',
    storageBucket: 'ase-urhg.firebasestorage.app',
    iosBundleId: 'com.example.myapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe8MB4e2P8OG_ydu5-lPQxqXQJUMqG3Ro',
    appId: '1:259364934462:ios:01ea01cdaefc24184d126f',
    messagingSenderId: '259364934462',
    projectId: 'ase-urhg',
    storageBucket: 'ase-urhg.firebasestorage.app',
    iosBundleId: 'com.example.myapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0wdVRwE_19E4pnOE8hUKC7h903UOEm78',
    appId: '1:259364934462:web:1b70b40efa7432764d126f',
    messagingSenderId: '259364934462',
    projectId: 'ase-urhg',
    authDomain: 'ase-urhg.firebaseapp.com',
    storageBucket: 'ase-urhg.firebasestorage.app',
    measurementId: 'G-08HLBG893M',
  );
}
